drop schema `soccerdb` ;

CREATE SCHEMA `soccerdb` ;

CREATE TABLE  `soccerdb`.`soccermatch` (
  `ID` bigint(20) unsigned NOT NULL ,
    
  `MODE` VARCHAR(10) NOT NULL,
  `NAME_TEAM1` VARCHAR(45),
  `NAME_TEAM2` VARCHAR(45),
  `SPREAD_BET_RESULT` TINYINT ,
  `OU_BET_RESULT` TINYINT ,
  
  `CURRENT_SPREAD_TEAM1` DECIMAL(6,3),
  `CURRENT_ODDS_TEAM1` DECIMAL(6,3),
  `OPEN_SPREAD_TEAM1` DECIMAL(6,3),
  `OPEN_ODDS_TEAM1` DECIMAL(6,3),
  `CURRENT_SPREAD_TEAM2` DECIMAL(6,3),
  `CURRENT_ODDS_TEAM2` DECIMAL(6,3),
  `OPEN_SPREAD_TEAM2` DECIMAL(6,3),
  `OPEN_ODDS_TEAM2` DECIMAL(6,3),
  
  `CURRENT_TOTAL_LINE` DECIMAL(6,3),
  `OPEN_TOTAL_LINE` DECIMAL(6,3),
  `CURRENT_OU_ODDS_TEAM1` DECIMAL(6,3),
  `OPEN_OU_ODDS_TEAM1` DECIMAL(6,3),
  `CURRENT_OU_ODDS_TEAM2` DECIMAL(6,3),
  `OPEN_OU_ODDS_TEAM2` DECIMAL(6,3),
  
  `SCORE_TEAM1` TINYINT unsigned,
  `SCORE_TEAM2` TINYINT unsigned,
  



  
  `CREATED_DATE` datetime NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

ALTER TABLE `soccerdb`.`soccermatch` 
ADD PRIMARY KEY (`ID`, `MODE`);

ALTER TABLE `soccerdb`.`soccermatch` 
ADD INDEX `index_over_under` (`MODE` ASC, `OU_BET_RESULT` ASC, `OPEN_TOTAL_LINE` ASC, `CURRENT_OU_ODDS_TEAM1` ASC, `OPEN_OU_ODDS_TEAM1` ASC, `CURRENT_OU_ODDS_TEAM2` ASC, `OPEN_OU_ODDS_TEAM2` ASC, `CURRENT_TOTAL_LINE` ASC),
ADD INDEX `index_spread_odds` (`CURRENT_SPREAD_TEAM1` ASC, `CURRENT_ODDS_TEAM1` ASC, `OPEN_SPREAD_TEAM1` ASC, `OPEN_ODDS_TEAM1` ASC, `CURRENT_SPREAD_TEAM2` ASC, `CURRENT_ODDS_TEAM2` ASC, `OPEN_SPREAD_TEAM2` ASC, `OPEN_ODDS_TEAM2` ASC, `SPREAD_BET_RESULT` ASC);

CREATE TABLE  `soccerdb`.`soccermatch_temp` (
  `ID` bigint(20) unsigned NOT NULL ,
    
  `MODE` VARCHAR(10) NOT NULL,
  `NAME_TEAM1` VARCHAR(45),
  `NAME_TEAM2` VARCHAR(45),
  `SPREAD_BET_RESULT` TINYINT ,
  `OU_BET_RESULT` TINYINT ,
  
  `SPREAD_BET_WIN_PERCENT` TINYINT ,
  `OU_BET_WIN_PERCENT` TINYINT ,
  `SPREAD_BET_TOTAL_COUNT` DECIMAL(6,3) ,
  `OU_BET_TOTAL_COUNT` DECIMAL(6,3) ,
  

  `CURRENT_SPREAD_TEAM1` DECIMAL(6,3),
  `CURRENT_ODDS_TEAM1` DECIMAL(6,3),
  `OPEN_SPREAD_TEAM1` DECIMAL(6,3),
  `OPEN_ODDS_TEAM1` DECIMAL(6,3),
  `CURRENT_SPREAD_TEAM2` DECIMAL(6,3),
  `CURRENT_ODDS_TEAM2` DECIMAL(6,3),
  `OPEN_SPREAD_TEAM2` DECIMAL(6,3),
  `OPEN_ODDS_TEAM2` DECIMAL(6,3),
  
  `CURRENT_TOTAL_LINE` DECIMAL(6,3),
  `OPEN_TOTAL_LINE` DECIMAL(6,3),
  `CURRENT_OU_ODDS_TEAM1` DECIMAL(6,3),
  `OPEN_OU_ODDS_TEAM1` DECIMAL(6,3),
  `CURRENT_OU_ODDS_TEAM2` DECIMAL(6,3),
  `OPEN_OU_ODDS_TEAM2` DECIMAL(6,3),
  
  `SCORE_TEAM1` TINYINT unsigned,
  `SCORE_TEAM2` TINYINT unsigned,
  
  `CREATED_DATE` datetime NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

ALTER TABLE `soccerdb`.`soccermatch_temp` 
ADD PRIMARY KEY (`ID`);

commit;
